title: "Chelsey Barhorst | Cincinnati Family and Portrait Photography"
author: "Chelsey Barhorst"
email: jordan.barhorst@gmail.com
keywords: "photography, family photography, portrait photography, cincinnati, ohio"
description: "Chelsey is a family and portrait photographer based in Cincinnati, Ohio."

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chelseybarhorstphotography.com" # the base hostname & protocol for your site

markdown: redcarpet
redcarpet:
  extensions: ["smart", "autolink", "tables", "no_intra_emphasis", "strikethrough", "underline", "quote", "footnotes"]

exclude: ['assets/src', 'node_modules', 'package.json', 'gulpfile.js', 'LICENSE', 'README.md', 'bourbonify-jekyll.sublime-project', 'bower_components', 'bower.json']

timezone: Eastern

permalink: none
